### ISSUE TITLE
Font weight is static everywhere

### ISSUE THREAD

**Issue by PackmanDude** [MinersStudios/WMSite#18]
Literally [1](https://github.com/MinersStudios/WMSite/issues/14)98[4](https://github.com/MinersStudios/WMSite/issues/14).

**Comment by p0loskun** [comment]
https://github.com/MinersStudios/WMSite/assets/74924188/52fea3d0-f9c0-440d-8f42-7a4dfd334ebe

**Comment by p0loskun** [comment]
завтра.

**Comment by PackmanDude** [comment]
@p0loskun can you not guess and download Firefox to test it? I disabled font-weight in main.css via dev tools, but I don’t think this should work like that at all.

**Comment by p0loskun** [comment]
> @p0loskun can you not guess and download Firefox to test what you commit? I fixed it on my machine by disabling `font-weight` in `main.css` via dev tools, but I don’t think this should work like that at all.

I accidentally returned the previous code and didnt doublecheck it when publishing it

**Comment by PackmanDude** [comment]
> I accidentally returned the previous code and didnt doublecheck it when publishing it

Poloskun doesn’t need to hear all this. He’s a highly trained professional.
