### ISSUE TITLE
Redesign using Svelte?

### ISSUE THREAD

**Issue by PackmanDude** [MinersStudios/WMSite#21]
https://svelte.dev

**Comment by p0loskun** [comment]
Why and what is the reason for this? 
I think it makes no sense to do any redesign at this point

**Comment by PackmanDude** [comment]
I meant internal redesign, not the look. Svelte lets you write less code, it is declarative and allows code to be more maintainable and less repetitive with self-contained reactive components and its fancy syntax. Take a look yourself at their tutorial, it will show you what features it has: https://svelte.dev/tutorial/basics. It is like vanilla JavaScript, but better. Svelte compiler will translate code into vanilla JavaScript, but with higher performance, because you use more high-level features this framework provides and let compiler do the work for you. I thought it would be beneficial to migrate to Svelte, because we lose nothing and get better performance with less code. And also components can be reused, which will also make code smaller. If we redesign the website with Svelte it will be more declarative and much smaller in code size. Also Svelte provides a plenty of transitions and animations and because of its reactivity, things like toasts, which website currently has would take inly a few lines of code and ve more modular, allowing us to more easily add updates to the website.

**Comment by PackmanDude** [comment]
I don't really know which point to bring, because it would fit really well for our website, making code less of a mess.

**Comment by p0loskun** [comment]
Okay, the proposal makes sense. I'll close this issue for now, with the possibility of revisiting it in the future if the time arises

**Comment by PackmanDude** [comment]
Why close? Leave it open to return to it.

**Comment by p0loskun** [comment]
I don't see the point in leaving the issue open for now. Besides, in the future it would be better to reconsider several options for "redesigning" the site and open a more appropriate issue for this case

**Comment by PackmanDude** [comment]
Uhh, it seems to me like you just do not want to deal with it yourself. I will make a pull request when I will be done with migration to Svelte, but I need you to open a new branch, so it would be easier to work with it and compare.

**Comment by p0loskun** [comment]
Why such radical conclusions? You are now no different from the same person whose activities you and I discussed in Discord

**Comment by PackmanDude** [comment]
> Why such radical conclusions? You are now no different from the same person whose activities you and I discussed in Discord

What?

**Comment by PackmanDude** [comment]
Which conclusions are you talking about?
